# AUTOGENERATED! DO NOT EDIT! File to edit: Chap2_InferenceApp_Gradio.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_images']

# %% Chap2_InferenceApp_Gradio.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% Chap2_InferenceApp_Gradio.ipynb 4
learn = load_learner("export.pkl")

# %% Chap2_InferenceApp_Gradio.ipynb 8
categories = ("ferrari","lamborghini","maserati")

def classify_images(img):
    pred,probs_idx,probs = learn.predict(img)
    return dict(zip(categories,map(float,probs))) #we need to convert tensors to float for gradio

# %% Chap2_InferenceApp_Gradio.ipynb 10
image = gr.Image()
label = gr.Label()
examples=["maserati.jpg","ferrari.jpg"]

intf = gr.Interface(fn=classify_images,inputs=image,outputs=label,examples=examples)
#local run of the app
intf.launch()
